--- 
project_name: Ruby-Verse
project_homepage: http://bitbucket.org/ged/ruby-verse
project_summary: A Ruby binding for Verse
project_description: |-
  This is a Ruby binding for the Verse network protocol. Verse a network 
  protocol that lets multiple applications act together as one large application by 
  sharing data over a network.
project_pubhost: deveiate
project_pubdir: /usr/local/www/public/code/
gem_pubhost: rubygems.org
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
release_smtphost: mail.faeriemud.org
post_install_message: ""
authors: 
  Michael Granger: ged@FaerieMUD.org
project_dependencies: {}

dev_dependencies: 
  rake-compiler: ">=0.7.0"
project_requirements: 
  Verse: ">= 0.6.1"
additional_pkgfiles: []

excluded_pkgfiles: []

version_file: verse.rb
